### ISSUE TITLE
Please add to the issue

### ISSUE THREAD

**Issue by tonygo** [adafruit/circuitpython-weekly-newsletter#447]
**Lissajous Curves with MicroPython on 320x240 pixel display with Pi Pico**

https://www.instructables.com/Lissajous-Curve/

https://www.youtube.com/watch?v=6cVF5D7NoTo

![Lissajous-7](https://user-images.githubusercontent.com/3583957/220691010-fb5e8c6a-3a3c-4040-bd8e-aea766cb11a5.jpg)

**Comment by TheKitty** [comment]
Added, thanks! Out tomorrow
