### ISSUE TITLE
Using a Capacitive Difference Sensor W01 to measure the depth of water in a glass vase without getting it wet.

### ISSUE THREAD

**Issue by tonygo** [adafruit/circuitpython-weekly-newsletter#450]
Using a Capacitive Difference Sensor W01 to measure the depth of water in a glass vase without getting it wet. Circuit, video and code

https://youtu.be/5OUG9Fc96Hk   

https://www.instructables.com/Water-Depth-Gauge-With-Capacitive-Difference-Senso/
![Cap Sensor-2](https://user-images.githubusercontent.com/3583957/223787328-008e06df-114c-4d7c-a98f-ba15881d991d.jpg)

**Comment by TheKitty** [comment]
Done, thank you for your submission!
