### ISSUE TITLE
Idea for 2019-08-20-draft.md

### ISSUE THREAD

**Issue by zrecore** [adafruit/circuitpython-weekly-newsletter#47]
## MicroPython port for 2MiB ESP32 devices in progress

Thanks to help from the MicroPython + Maker community, it looks like there is a path towards adding built-in support for MicroPython on 2MiB ESP32 devices. We are currently looking for people to try out the changes on 2MiB ESP32 devices (such as the ESP32-D2WD) to see what breaks.

https://github.com/micropython/micropython/pull/4987

**Comment by TheKitty** [comment]
Info added. For faster integration, we encourage contributors to use the Pull Request feature where the info has already been added.

Thanks for your contribution!

**Comment by TheKitty** [comment]
Link to posted info 
https://www.adafruitdaily.com/2019/08/20/consumers-should-immediately-python-the-circuit-python-adafruit-circuitpython-pythonhardware-circuitpython-micropython-thepsf-adafruit/
