### ISSUE TITLE
Request for 2019-09-03-draft.md

### ISSUE THREAD

**Issue by carlosperate** [adafruit/circuitpython-weekly-newsletter#49]
Not sure where the best section for this might be, so I hope it's okay to submit this as an issue instead.

Would it be possible to add this to the newsletter? https://twitter.com/carlosperate/status/1166689186457542656

It's a call for PyCon UK attendees to bring their Python on Hardware projects to an open session. We had a similar session one year and people brought a lot of cool projects (including plenty of CircuitPython!) so I'm really looking forward to see as many people as possible bringing their cool projects again this year :)

**Comment by ptorrone** [comment]
yep, all good, we'll add it!
