### ISSUE TITLE
Bluetooth (BLE) communication between 2 Pico Ws using MicroPython

### ISSUE THREAD

**Issue by tonygo** [adafruit/circuitpython-weekly-newsletter#495]
Please include:
This video demonstrates the passing of data wirelessly from a set of three 10K ohm potentiometers on one Pico W to a Neopixel strip on another Pico W using Bluetooth (BLE) protocols. Using Bluetooth method is fast and reliable and does not need access to a WiFi network. https://youtu.be/V7spAtwrQIY Easy to do and pretty fast using MicroPython for the code.

**Comment by TheKitty** [comment]
Will look at it, thanks!
