### ISSUE TITLE
Pi Pico Robotics with Mecanum Wheels

### ISSUE THREAD

**Issue by tonygo** [adafruit/circuitpython-weekly-newsletter#511]
Please add a link to:

**Pico Robotics with Mecanum Wheels**

Video: https://youtu.be/WphaBtJ2VsU
Code and Method: https://thepihut.com/blogs/raspberry-pi-tutorials/build-a-raspberry-pi-pico-robot-with-mecanum-wheels

Thank you

**Comment by TheKitty** [comment]
Now in this coming issue, thanks!
